language: perl
perl:
    - "5.30"
    - "5.28"
    - "5.26"
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.14"
    - "5.12"
    - "5.10"

install:
    - sudo apt install sqlite3
    - cpanm --quiet --installdeps --notest .
    - carton install
    - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov

script:
    - "perl ./script/neurolandia_catalyst_migrate.pl"
    - "perl ./script/neurolandia_catalyst_test_more.pl --verbose"
    - "perl ./script/neurolandia_catalyst_test_more.pl --verbose --use_carton"
    - "carton exec perl ./script/neurolandia_catalyst_test_more.pl --verbose --use_carton"
    - cover -delete
    - HARNESS_PERL_SWITCHES="-MDevel::Cover=+ignore,^local/|^t/" ./script/neurolandia_catalyst_test_more"

after_success:
    - cover -report codecov

notifications:
    email: false
