language: perl
perl:
    - "5.30"
    - "5.28"
    - "5.26"
    - "5.24"
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.14"
    - "5.12"
    - "5.10"

install:
    - sudo apt install sqlite3
    - cpanm --quiet --installdeps --notest .
    - carton install
    - cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov

script:
    - "rm -rf ./lib/NCSchema* ./lib/Neurolandia/Catalyst/Model/NCModel.pm t/model*"
    - "perl ./script/neurolandia_catalyst_migration.pl --migrate_and_populate"
    - "perl ./script/neurolandia_catalyst_test_more.pl --verbose"
    - "perl ./script/neurolandia_catalyst_test_more.pl --verbose --use_carton"
    - "carton exec perl ./script/neurolandia_catalyst_test_more.pl --verbose --use_carton"
    - "perl Makefile.PL"
    - cover -test

after_success:
    - cover -report codecov

notifications:
    email: false
