PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS author(
   id INTEGER PRIMARY KEY,
   username VARCHAR(255) NOT NULL,
   email_address VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS post(
    id INTEGER PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(255) NOT NULL,
    author_id INTEGER REFERENCES author(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);
