PRAGMA foreign_keys = ON;
CREATE TABLE IF NOT EXISTS user(
   id INTEGER PRIMARY KEY,
   username VARCHAR(255) NOT NULL,
   email_address VARCHAR(255) NOT NULL,
   password VARCHAR(255) NOT NULL,
   role VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS post(
    id INTEGER PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    content VARCHAR(255) NOT NULL,
    create_date datetime NOT NULL,
    user_id INTEGER REFERENCES user(id)
    ON DELETE CASCADE ON UPDATE CASCADE
);
